<?php

if (!defined('ABSPATH')) exit;

const PRINTAGO_TWILIO_ACCOUNT_SID = "";
const PRINTAGO_TWILIO_AUTH_TOKEN = "";
const PRINTAGO_WEBHOOK_API_KEY = "";
const PRINTAGO_WEBHOOK_FROM = "+11234567890";
const PRINTAGO_WEBHOOK_RECIPIENTS = [
    '+11234567890'
];